# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app


# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed dependencies specified in requirements.txt
RUN pip install --no-cache-dir kafka-python websockets json asyncio

# Expose the port the server runs on
EXPOSE 5000

# Run the backend server when the container launches
CMD ["python", "server.py"]

